# Config file

# Import libraries
import os

BASEDIR = os.path.dirname('.')

# TEMPORAL DATABASE
TEMPORAL_DB_SERVER = '127.0.0.1'
TEMPORAL_DB_PORT = '27017'

# AFTER-PROCESSING DATABASE


# NETWORK
NETWORK_INTERFACE = 'enp0s25'
PROTOCOLS_FILE = BASEDIR + 'Protocols'

# QUEUE
TCP_NUMBER_PROCESS = 10
UDP_NUMBER_PROCESS = 2
ICMP_NUMBER_PROCESS = 1
