# File to define the global variables

# FLOW STATUS
FLOW_UPDATING = 1
FLOW_STANDBY = 2
FLOW_FINISHED = 3
FLOW_ARCHIVED = 4

# FLOW AI PROCESSING STATUS
FLOW_AI_PS12_NOT_STARTED = 1
FLOW_AI_PS12_WORKING = 2
FLOW_AI_PS12_WAITING = 3
FLOW_AI_PS12_FINISHED = 4

# FLOW AI RESULT
FLOW_AI_PS12_POSITIVE = 1
FLOW_AI_PS12_NEGATIVE = 2
FLOW_AI_PS12_SUSPECT = 3

