# File to define the global variables

# CONVERSATION FLOW STATUS
CONVERSATION_FLOW_UPDATING = 1
CONVERSATION_FLOW_STANDBY = 2
CONVERSATION_FLOW_FINISHED = 3
CONVERSATION_FLOW_ARCHIVED = 4

# CONVERSATION AI PROCESSING STATUS
CONVERSATION_AI_PS12_NOT_STARTED = 1
CONVERSATION_AI_PS12_WORKING = 2
CONVERSATION_AI_PS12_WAITING = 3
CONVERSATION_AI_PS12_FINISHED = 4

# CONVERSATION AI RESULT
CONVERSATION_AI_PS12_POSITIVE = 1
CONVERSATION_AI_PS12_NEGATIVE = 2
CONVERSATION_AI_PS12_SUSPECT = 3

